const USERS={KMBD:{pass:'ausbilder1',role:'Ausbilder'},Leitung:{pass:'leitung123',role:'Leitung'},'Anwärter':{pass:'test123',role:'Anwärter'}};
let currentUser=null,z=20;const $=s=>document.querySelector(s),store=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const apps=[
{id:'dash',name:'Dashboard',icon:'📊',x:80,y:70,render:dashboard},{id:'einsatz',name:'Einsätze',icon:'🚨',render:einsaetze},{id:'personal',name:'Personalakten',icon:'👥',render:personal},{id:'dienst',name:'Dienstplan',icon:'📅',render:dienstplan},{id:'chat',name:'Interner Chat',icon:'💬',render:chat},{id:'form',name:'Formulare',icon:'📝',render:formulare},{id:'mat',name:'Material',icon:'📦',render:material},{id:'fahr',name:'Fahrzeuge',icon:'🚔',render:fahrzeuge},{id:'lex',name:'Lexikon',icon:'📚',render:lexikon},{id:'files',name:'Dokumente',icon:'📁',render:dokumente},{id:'settings',name:'Einstellungen',icon:'⚙️',render:settings},{id:'help',name:'Anleitung',icon:'❔',render:help}];
let data=load('kmbdData',{einsatz:[['KB-2026-014','Köln-Mitte','Sichtung / Absperrung','Offen','Priorität 2'],['KB-2026-013','Hafen','Ausbildungslage','In Bearbeitung','Übung'],['KB-2026-012','Chorweiler','Nachkontrolle','Abgeschlossen','Dokumentiert']],personal:[['K. Weber','Leitung','Aktiv','Ausbilder'],['M. Yilmaz','Truppführer','Aktiv','Fortgeschritten'],['L. Hartmann','Anwärter','Probezeit','Grundausbildung']],material:[['Absperrband','24 Rollen','OK'],['Schutzanzüge','8 Sets','Prüfen'],['Dokumentationskamera','3 Stück','OK'],['Markierungsset','5 Kisten','OK']],chat:[['System','Willkommen im internen KMBD-Chat. Nachrichten werden in dieser Demo lokal im Browser gespeichert.']]});
function applyPrefs(){let p=load('prefs',{theme:'dark',wall:'kmbd'});document.body.className=p.theme;document.documentElement.style.setProperty('--wallpaper',`url('../assets/wallpapers/${p.wall==='light'?'light':p.wall==='blue'?'blue':'kmbd-red'}.svg')`)}
function login(){let u=$('#loginUser').value.trim(),p=$('#loginPass').value;if(USERS[u]?.pass===p){currentUser={name:u,role:USERS[u].role};$('#loginScreen').classList.add('hidden');$('#desktop').classList.remove('hidden');boot()}else $('#loginError').textContent='Login nicht korrekt.'}
function boot(){applyPrefs();$('#trayUser').textContent=currentUser.name;$('#startUser').textContent=currentUser.role;renderIcons();tick();setInterval(tick,1000);openApp('dash')}
function tick(){let d=new Date();$('#clock').textContent=d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('#trayTime').textContent=d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
function renderIcons(){let di=$('#desktopIcons'),sg=$('#startApps');di.innerHTML=sg.innerHTML='';apps.forEach(a=>{di.innerHTML+=`<button class="icon" ondblclick="openApp('${a.id}')" onclick="openApp('${a.id}')"><div class="ico">${a.icon}</div><span>${a.name}</span></button>`;sg.innerHTML+=`<button class="start-tile" onclick="openApp('${a.id}')"><div class="ico">${a.icon}</div><span>${a.name}</span></button>`})}
function openApp(id){let a=apps.find(x=>x.id===id),old=document.querySelector(`[data-win="${id}"]`);if(old){old.style.zIndex=++z;old.classList.remove('hidden');return}let w=document.createElement('div');w.className='window glass';w.dataset.win=id;w.style.left=(180+Math.random()*180)+'px';w.style.top=(70+Math.random()*80)+'px';w.innerHTML=`<div class="titlebar"><span>${a.icon}</span><b>${a.name}</b><div class="win-actions"><button onclick="minWin('${id}')">—</button><button onclick="maxWin('${id}')">□</button><button onclick="closeWin('${id}')">×</button></div></div><div class="win-body">${a.render()}</div>`;$('#windows').appendChild(w);makeDrag(w);taskButton(a);w.style.zIndex=++z}
function taskButton(a){if(document.querySelector(`[data-task="${a.id}"]`))return;$('#taskApps').innerHTML+=`<button class="task-app" data-task="${a.id}" onclick="openApp('${a.id}')" title="${a.name}">${a.icon}</button>`}
function closeWin(id){document.querySelector(`[data-win="${id}"]`)?.remove();document.querySelector(`[data-task="${id}"]`)?.remove()}function minWin(id){document.querySelector(`[data-win="${id}"]`)?.classList.add('hidden')}function maxWin(id){document.querySelector(`[data-win="${id}"]`)?.classList.toggle('max')}
function makeDrag(w){let bar=w.querySelector('.titlebar'),dx=0,dy=0,drag=false;bar.onmousedown=e=>{if(e.target.tagName==='BUTTON')return;drag=true;dx=e.clientX-w.offsetLeft;dy=e.clientY-w.offsetTop;w.style.zIndex=++z};document.onmousemove=e=>{if(!drag||w.classList.contains('max'))return;w.style.left=Math.max(0,e.clientX-dx)+'px';w.style.top=Math.max(0,e.clientY-dy)+'px'};document.onmouseup=()=>drag=false}
function dashboard(){return `<div class="grid cards"><div class="card"><h3>Aktive Lage</h3><div class="widget-big">3</div><p class="muted">offene Vorgänge</p></div><div class="card"><h3>Bereitschaft</h3><div class="widget-big">Grün</div><p class="muted">Dienstbetrieb normal</p></div><div class="card"><h3>Ausbildung</h3><div class="widget-big">KB-02</div><p class="muted">nächster Block</p></div><div class="card"><h3>Chat</h3><div class="widget-big">${data.chat.length}</div><p class="muted">lokale Nachrichten</p></div></div><br><div class="split"><div class="card"><h3>Lageübersicht</h3><p>Dieses Portal ist für deinen GTA-RP KMBD gedacht: Verwaltung, Dienstplanung, RP-Dokumentation, Personalakten, Ausbildungsstand und interne Kommunikation.</p><p class="muted">Hinweis: Alles ist eine lokale Demo ohne echte Datenbank. Für echten Mehrbenutzer-Chat brauchst du später ein Backend.</p></div><div class="card"><h3>Schnellaktionen</h3><button class="btn" onclick="openApp('einsatz')">Neuen Einsatz vorbereiten</button> <button class="btn" onclick="openApp('chat')">Chat öffnen</button> <button class="btn" onclick="openApp('settings')">Design ändern</button></div></div>`}
function table(rows,heads){return `<table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function einsaetze(){return `<div class="toolbar"><button class="btn" onclick="addEinsatz()">+ RP-Einsatz anlegen</button><button class="btn">Export vorbereiten</button></div>${table(data.einsatz,['Aktenzeichen','Ort','Art','Status','Notiz'])}<div class="card"><h3>Dokumentationshinweise</h3><p class="muted">Für RP: Ort, Melder, beteiligte Einheiten, Maßnahmen, Ergebnis und Freigabe sauber eintragen. Keine echten Einsatzdaten verwenden.</p></div>`}
function addEinsatz(){let nr='KB-2026-'+String(Math.floor(Math.random()*900+100));data.einsatz.unshift([nr,'Neuer Ort','RP-Lage','Entwurf','bitte ergänzen']);store('kmbdData',data);refresh('einsatz')}
function personal(){return `<div class="toolbar"><button class="btn" onclick="addPerson()">+ Mitglied</button></div>${table(data.personal,['Name','Rang','Status','Qualifikation'])}<div class="card"><h3>Personalakte</h3><p class="muted">Beinhaltet in dieser Demo: Dienstgrad, Ausbildungsstand, Verwarnungen, Fortbildungen, Notizen und RP-Zugehörigkeit.</p></div>`}
function addPerson(){data.personal.push(['Neues Mitglied','Anwärter','Probezeit','Einweisung offen']);store('kmbdData',data);refresh('personal')}
function dienstplan(){return `<div class="grid cards"><div class="card"><h3>Montag</h3><p>20:00 Ausbildungsdienst</p><span class="pill">KB-Grundlagen</span></div><div class="card"><h3>Mittwoch</h3><p>19:30 Streifenunterstützung</p><span class="pill">Bereitschaft</span></div><div class="card"><h3>Samstag</h3><p>21:00 Szenarioabend</p><span class="pill">Großlage RP</span></div></div>`}
function chat(){return `<div class="chat-log" id="chatLog">${data.chat.map((m,i)=>`<div class="msg ${m[0]===currentUser.name?'me':''}"><b>${m[0]}</b><br>${m[1]}</div>`).join('')}</div><div class="chat-input"><input id="chatText" placeholder="Nachricht schreiben..."><button class="btn" onclick="sendChat()">Senden</button></div><p class="muted">Demo: lokal gespeichert. Für echten Live-Chat später z.B. Firebase, Supabase oder Node.js.</p>`}
function sendChat(){let t=$('#chatText').value.trim();if(!t)return;data.chat.push([currentUser.name,t]);store('kmbdData',data);refresh('chat')}
function formulare(){return `<div class="grid cards"><div class="card"><h3>KB-01 Einsatzbericht</h3><p class="muted">Grundformular für RP-Lagen.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-02 Ausbildung</h3><p class="muted">Nachweis Ausbildungsblock.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-03 Material</h3><p class="muted">Ausgabe/Rückgabe.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-04 Personalnotiz</h3><p class="muted">Interne RP-Verwaltung.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-05 Beschwerde</h3><p class="muted">Dienstaufsicht im RP.</p><button class="btn">Öffnen</button></div></div>`}
function material(){return table(data.material,['Material','Bestand','Status'])+`<div class="card"><h3>Lagerhinweis</h3><p class="muted">Bestände sind Demo-Werte. Später kann daraus ein echtes Inventarsystem entstehen.</p></div>`}
function fahrzeuge(){return table([['KMBD-01','SUV','Einsatzbereit','Garage Köln'],['KMBD-02','Transporter','Wartung','Werkstatt'],['KMBD-03','Führung','Einsatzbereit','Garage Köln']],['Kennung','Typ','Status','Standort'])}
function lexikon(){return `<div class="grid cards"><div class="card"><h3>RP-Sicherheit</h3><p>Absperren, Lage melden, Dokumentation führen, Freigabe abwarten.</p></div><div class="card"><h3>Funkdisziplin</h3><p>Kurze, klare Meldungen. Keine OOC-Informationen in IC-Kanälen.</p></div><div class="card"><h3>Ausbildung</h3><p>Grundlagen, Einsatzabläufe, Dokumentation, Teamführung.</p></div><div class="card"><h3>Abkürzungen</h3><p>KB = KMBD-Bericht, PA = Personalakte, DL = Dienstleitung.</p></div></div>`}
function dokumente(){return `<div class="grid cards"><div class="card"><h3>Dienstanweisung</h3><p class="muted">Regeln und Struktur für den KMBD.</p></div><div class="card"><h3>Ausbildungskonzept</h3><p class="muted">Module für Anwärter und Fortgeschrittene.</p></div><div class="card"><h3>Vorlagen</h3><p class="muted">Berichte, Notizen, Protokolle.</p></div></div>`}
function settings(){let p=load('prefs',{theme:'dark',wall:'kmbd'});return `<div class="split"><div class="card"><h3>Darstellung</h3><label>Modus<select id="themeSel"><option value="dark">Dunkel</option><option value="light">Hell</option><option value="contrast">Kontrast</option></select></label><button class="btn" onclick="saveTheme()">Speichern</button></div><div class="card"><h3>Hintergrund</h3><div class="wallpapers"><button class="wallpaper-choice ${p.wall==='kmbd'?'active':''}" style="background-image:url('assets/wallpapers/kmbd-red.svg')" onclick="setWall('kmbd')"></button><button class="wallpaper-choice ${p.wall==='blue'?'active':''}" style="background-image:url('assets/wallpapers/blue.svg')" onclick="setWall('blue')"></button><button class="wallpaper-choice ${p.wall==='light'?'active':''}" style="background-image:url('assets/wallpapers/light.svg')" onclick="setWall('light')"></button></div><p class="muted">Der rote Hintergrund ist an dein gesendetes Bild angelehnt und als auswählbarer KMBD-Hintergrund enthalten.</p></div></div>`}
function saveTheme(){let p=load('prefs',{theme:'dark',wall:'kmbd'});p.theme=$('#themeSel').value;store('prefs',p);applyPrefs()}function setWall(w){let p=load('prefs',{theme:'dark',wall:'kmbd'});p.wall=w;store('prefs',p);applyPrefs();refresh('settings')}
function help(){return `<div class="card"><h3>Start für Laien</h3><ol><li>ZIP herunterladen und entpacken.</li><li>Den Ordner <b>kmbd-portal-desktop-pro</b> in deinen GitHub-Desktop-Ordner legen.</li><li>GitHub Desktop öffnen.</li><li>Beschreibung eingeben, z.B. <b>Neue Desktop-Version</b>.</li><li><b>Commit to main</b> klicken.</li><li><b>Push origin</b> klicken.</li></ol><p class="muted">Die Website startet über index.html. Für GitHub Pages muss diese Datei im Hauptordner liegen.</p></div>`}
function refresh(id){let w=document.querySelector(`[data-win="${id}"] .win-body`),a=apps.find(x=>x.id===id);if(w)w.innerHTML=a.render()}
$('#loginBtn').onclick=login;$('#loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#startBtn').onclick=()=>$('#startMenu').classList.toggle('hidden');$('#logoutBtn').onclick=()=>location.reload();applyPrefs();
