const USERS={KMBD:{pass:'ausbilder1',role:'Master'},Leitung:{pass:'leitung123',role:'Leitung'},'Anwärter':{pass:'test123',role:'Anwärter'}};
let currentUser=null,z=30;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const initial={
  events:[
    {id:'KB-2026-021',type:'Einsatz',title:'Absicherung Innenstadt',date:'2026-07-01',time:'20:00',place:'Köln Innenstadt',status:'Geplant',lead:'Leitung',note:'Briefing 15 Minuten vor Beginn.'},
    {id:'KB-2026-022',type:'Übung',title:'Einweisung Dokumentation',date:'2026-07-03',time:'19:30',place:'Ausbildungsraum',status:'Vorbereitung',lead:'KMBD',note:'Teilnahme für neue Mitglieder empfohlen.'}
  ],
  personnel:[
    ['KMBD','Ausbilder','Aktiv','Leitung / Ausbildung'],['M. Schneider','Hauptkommissar','Aktiv','Einsatzführung'],['L. Weber','Kommissar','Aktiv','Dokumentation'],['T. Kaya','Anwärter','Probezeit','Grundausbildung']
  ],
  board:[['Dienstleitung','Neue Dienstanweisung ist im Dokumentenbereich hinterlegt.'],['Ausbildung','Nächste Einweisung findet Freitag um 19:30 Uhr statt.']],
  chat:[['System','Willkommen im internen KMBD-Chat.'],['Leitung','Bitte Termine und Übungen über die Terminverwaltung eintragen.']],
  notes:['Berichte zeitnah abschließen.','Teilnehmerlisten nach Übungen ergänzen.']
};
let data=load('kmbdDataV2',initial);
const apps=[
{id:'dash',name:'Dashboard',icon:'📊',render:dashboard},{id:'termine',name:'Termine & Einsätze',icon:'📅',render:termine},
{id:'personal',name:'Personalakten',icon:'👥',render:personal},{id:'dienst',name:'Dienstplan',icon:'🗓️',render:dienstplan},
{id:'chat',name:'Interner Chat',icon:'💬',render:chat},{id:'form',name:'Formulare',icon:'📝',render:formulare},
{id:'docs',name:'Dokumente',icon:'📁',render:dokumente},{id:'board',name:'Schwarzes Brett',icon:'📌',render:board},
{id:'stats',name:'Statistik',icon:'📈',render:stats},{id:'lex',name:'Lexikon',icon:'📚',render:lexikon},
{id:'admin',name:'Verwaltung',icon:'🛡️',render:admin},{id:'settings',name:'Einstellungen',icon:'⚙️',render:settings}
];
function login(){const u=$('#loginUser').value.trim(),p=$('#loginPass').value; if(!USERS[u]||USERS[u].pass!==p){$('#loginError').textContent='Login fehlgeschlagen.';return} currentUser={name:u,role:USERS[u].role}; $('#loginScreen').classList.add('hidden'); $('#desktop').classList.remove('hidden'); $('#trayUser').textContent=`${u} · ${currentUser.role}`; $('#startUser').textContent=u; renderIcons(); tick(); setInterval(tick,1000); applyPrefs(); updateWidgets(); openApp('dash')}
function tick(){let d=new Date();$('#clockBig').textContent=d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});$('#trayTime').textContent=d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
function canMaster(){return currentUser&&currentUser.role==='Master'}
function renderIcons(){let d=$('#desktopIcons'),s=$('#startApps');d.innerHTML=s.innerHTML=''; apps.forEach(a=>{d.innerHTML+=`<button class="icon" onclick="openApp('${a.id}')"><div class="ico">${a.icon}</div><span>${a.name}</span></button>`;s.innerHTML+=`<button class="start-tile" onclick="openApp('${a.id}')"><div class="ico">${a.icon}</div><span>${a.name}</span></button>`})}
function openApp(id){let a=apps.find(x=>x.id===id),old=document.querySelector(`[data-win="${id}"]`); $('#startMenu').classList.add('hidden'); if(old){old.classList.remove('hidden');old.style.zIndex=++z;return} let w=document.createElement('div'); w.className='window glass';w.dataset.win=id;w.style.left=(150+Math.random()*160)+'px';w.style.top=(55+Math.random()*80)+'px';w.innerHTML=`<div class="titlebar"><span>${a.icon}</span><b>${a.name}</b><div class="win-actions"><button onclick="minWin('${id}')">—</button><button onclick="maxWin('${id}')">□</button><button onclick="closeWin('${id}')">×</button></div></div><div class="win-body">${a.render()}</div>`; $('#windows').appendChild(w); makeDrag(w); addTask(a); w.style.zIndex=++z}
function addTask(a){if($(`[data-task="${a.id}"]`))return; $('#taskApps').innerHTML+=`<button class="task-app" data-task="${a.id}" onclick="openApp('${a.id}')" title="${a.name}">${a.icon}</button>`}
function closeWin(id){$(`[data-win="${id}"]`)?.remove();$(`[data-task="${id}"]`)?.remove()} function minWin(id){$(`[data-win="${id}"]`)?.classList.add('hidden')} function maxWin(id){$(`[data-win="${id}"]`)?.classList.toggle('max')}
function makeDrag(w){let bar=w.querySelector('.titlebar'),drag=false,dx=0,dy=0;bar.onmousedown=e=>{if(e.target.tagName==='BUTTON')return;drag=true;dx=e.clientX-w.offsetLeft;dy=e.clientY-w.offsetTop;w.style.zIndex=++z};document.addEventListener('mousemove',e=>{if(!drag||w.classList.contains('max'))return;w.style.left=Math.max(0,e.clientX-dx)+'px';w.style.top=Math.max(0,e.clientY-dy)+'px'});document.addEventListener('mouseup',()=>drag=false)}
function refresh(id){let a=apps.find(x=>x.id===id),b=$(`[data-win="${id}"] .win-body`); if(b)b.innerHTML=a.render(); updateWidgets()}
function table(rows,heads){return `<table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function eventRows(){return data.events.map(e=>[e.id,e.type,e.title,`${e.date}<br>${e.time}`,e.place,e.status,e.lead])}
function dashboard(){return `<div class="grid cards"><div class="card"><h3>Offene Vorgänge</h3><div class="big">${data.events.filter(e=>e.status!=='Abgeschlossen').length}</div><p class="muted">Einsätze und Übungen</p></div><div class="card"><h3>Personal</h3><div class="big">${data.personnel.length}</div><p class="muted">aktive Einträge</p></div><div class="card"><h3>Chat</h3><div class="big">${data.chat.length}</div><p class="muted">Nachrichten lokal gespeichert</p></div><div class="card"><h3>System</h3><div class="big">Online</div><p class="muted">lokale Portal-Demo</p></div></div><br><div class="split"><div class="card"><h3>Lageübersicht</h3><p>Interner Arbeitsbereich für Terminplanung, Einsatzverwaltung, Ausbildungsorganisation, Personalakten, Dokumente und Kommunikation.</p><p class="muted">Master-Benutzer können Termine, Einsätze und Übungen selbst anlegen.</p></div><div class="card"><h3>Schnellzugriff</h3><button class="btn" onclick="openApp('termine')">Termin anlegen</button> <button class="btn" onclick="openApp('chat')">Chat öffnen</button> <button class="btn" onclick="openApp('settings')">Design ändern</button></div></div>`}
function termine(){let form=canMaster()?`<div class="card"><h3>Neuen Termin anlegen</h3><div class="form-grid"><label>Art<select id="evType"><option>Einsatz</option><option>Übung</option><option>Besprechung</option><option>Ausbildung</option></select></label><label>Titel<input id="evTitle" placeholder="z.B. Übung Dokumentation"></label><label>Datum<input id="evDate" type="date"></label><label>Uhrzeit<input id="evTime" type="time"></label><label>Ort<input id="evPlace" placeholder="z.B. Präsidium Köln"></label><label>Status<select id="evStatus"><option>Geplant</option><option>Vorbereitung</option><option>Laufend</option><option>Abgeschlossen</option></select></label><label class="full">Notiz<textarea id="evNote" placeholder="Briefing, Teilnehmer, Hinweise..."></textarea></label></div><button class="primary" onclick="addEvent()">Termin speichern</button></div>`:`<div class="card"><h3>Terminverwaltung</h3><p class="muted">Nur der Master-Zugang kann neue Einsätze und Übungen anlegen.</p></div>`; return `<div class="split"><div><div class="toolbar"><button class="btn" onclick="sortEvents()">Nach Datum sortieren</button></div>${table(eventRows(),['Az.','Art','Titel','Datum','Ort','Status','Leitung'])}</div>${form}</div>`}
function addEvent(){let ev={id:'KB-'+new Date().getFullYear()+'-'+String(Math.floor(Math.random()*900+100)),type:$('#evType').value,title:$('#evTitle').value.trim()||'Neuer Termin',date:$('#evDate').value||new Date().toISOString().slice(0,10),time:$('#evTime').value||'20:00',place:$('#evPlace').value.trim()||'Köln',status:$('#evStatus').value,lead:currentUser.name,note:$('#evNote').value.trim()};data.events.unshift(ev);store('kmbdDataV2',data);refresh('termine');refresh('dash')}
function sortEvents(){data.events.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));store('kmbdDataV2',data);refresh('termine')}
function personal(){return `<div class="toolbar"><button class="btn" onclick="addPerson()">+ Eintrag</button></div>${table(data.personnel,['Name','Rang','Status','Qualifikation'])}<div class="card"><h3>Personalakte</h3><p class="muted">Vorgesehen für Rang, Ausbildungsstand, Dienstnotizen, Teilnahme an Übungen und interne Freigaben.</p></div>`}
function addPerson(){if(!canMaster())return alert('Nur Master kann Personal ergänzen.');data.personnel.push(['Neues Mitglied','Anwärter','In Prüfung','Einweisung offen']);store('kmbdDataV2',data);refresh('personal')}
function dienstplan(){return `<div class="grid cards"><div class="card"><h3>Montag</h3><p>20:00 Ausbildungsdienst</p><span class="pill">Grundlagen</span></div><div class="card"><h3>Mittwoch</h3><p>19:30 Bereitschaft</p><span class="pill">Dienstbetrieb</span></div><div class="card"><h3>Freitag</h3><p>19:30 Übung / Besprechung</p><span class="pill">Team</span></div><div class="card"><h3>Samstag</h3><p>21:00 Sonderlage nach Ansage</p><span class="pill">Optional</span></div></div>`}
function chat(){return `<div class="chat-layout"><div><div class="chat-log" id="chatLog">${data.chat.map(m=>`<div class="msg ${m[0]===currentUser.name?'me':''}"><b>${m[0]}</b><br>${m[1]}</div>`).join('')}</div><div class="chat-input"><input id="chatText" placeholder="Nachricht schreiben..."><button class="btn" onclick="sendChat()">Senden</button></div></div><div class="card online-list"><h3>Online</h3><div>🟢 ${currentUser.name}</div><div>🟢 Leitung</div><div>🟡 Dienstgruppe</div><p class="muted">Demo-Chat: lokal im Browser gespeichert.</p></div></div>`}
function sendChat(){let t=$('#chatText').value.trim();if(!t)return;data.chat.push([currentUser.name,t]);store('kmbdDataV2',data);refresh('chat')}
function formulare(){return `<div class="grid cards"><div class="card"><h3>KB-01 Einsatzbericht</h3><p class="muted">Lage, Ort, Beteiligte, Maßnahmen, Abschluss.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-02 Übungsnachweis</h3><p class="muted">Thema, Teilnehmer, Lernziel, Ergebnis.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-03 Dienstnotiz</h3><p class="muted">Interne Notiz zur Nachverfolgung.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-04 Personalvermerk</h3><p class="muted">Ausbildung, Verhalten, Empfehlung.</p><button class="btn">Öffnen</button></div><div class="card"><h3>KB-05 Besprechungsprotokoll</h3><p class="muted">Beschlüsse und Aufgaben.</p><button class="btn">Öffnen</button></div></div>`}
function dokumente(){return `<div class="grid cards"><div class="card"><h3>Dienstanweisung</h3><p>Struktur, Zuständigkeiten und interne Abläufe.</p></div><div class="card"><h3>Ausbildungskonzept</h3><p>Einweisung, Fortbildung und Prüfungsstand.</p></div><div class="card"><h3>Vorlagen</h3><p>Berichte, Protokolle und Personalnotizen.</p></div><div class="card"><h3>Archiv</h3><p>Abgeschlossene Vorgänge und ältere Dokumente.</p></div></div>`}
function board(){let add=canMaster()?`<div class="chat-input"><input id="boardText" placeholder="Neue Bekanntmachung"><button class="btn" onclick="addBoard()">Eintragen</button></div>`:'';return `<div class="card"><h3>Schwarzes Brett</h3>${data.board.map(b=>`<div class="msg"><b>${b[0]}</b><br>${b[1]}</div>`).join('')}${add}</div>`}
function addBoard(){let t=$('#boardText').value.trim();if(!t)return;data.board.unshift([currentUser.name,t]);store('kmbdDataV2',data);refresh('board')}
function stats(){return `<div class="grid cards"><div class="card"><h3>Geplante Termine</h3><div class="big">${data.events.filter(e=>e.status==='Geplant').length}</div></div><div class="card"><h3>Übungen</h3><div class="big">${data.events.filter(e=>e.type==='Übung').length}</div></div><div class="card"><h3>Einsätze</h3><div class="big">${data.events.filter(e=>e.type==='Einsatz').length}</div></div><div class="card"><h3>Abgeschlossen</h3><div class="big">${data.events.filter(e=>e.status==='Abgeschlossen').length}</div></div></div>`}
function lexikon(){return `<div class="grid cards"><div class="card"><h3>Ablauf Einsatz</h3><p>Annahme, Briefing, Anfahrt, Absicherung, Dokumentation, Abschlussmeldung.</p></div><div class="card"><h3>Dokumentation</h3><p>Jeder Vorgang erhält Aktenzeichen, Ort, Zeit, Leitung, Ergebnis und Nachverfolgung.</p></div><div class="card"><h3>Ausbildung</h3><p>Einweisung, Begleitung, Prüfungsvorbereitung und Freigabe durch Leitung.</p></div><div class="card"><h3>Abkürzungen</h3><p>KB = KMBD-Bericht, PA = Personalakte, DL = Dienstleitung.</p></div></div>`}
function admin(){return `<div class="card"><h3>Verwaltung</h3><p>Angemeldet als <b>${currentUser.name}</b> mit Rolle <b>${currentUser.role}</b>.</p><p class="muted">Master kann Termine, Personal und Bekanntmachungen ergänzen.</p><button class="btn" onclick="resetDemo()">Lokale Demo-Daten zurücksetzen</button></div>`}
function resetDemo(){if(confirm('Demo-Daten wirklich zurücksetzen?')){localStorage.removeItem('kmbdDataV2');data=structuredClone(initial);refresh('admin');refresh('dash');updateWidgets()}}
function settings(){let p=load('prefsV2',{theme:'dark',wall:'kmbd'});return `<div class="split"><div class="card"><h3>Designmodus</h3><label>Modus<select id="themeSel"><option value="dark">Dunkel</option><option value="light">Hell</option><option value="contrast">Kontrast</option></select></label><button class="btn" onclick="saveTheme()">Speichern</button></div><div class="card"><h3>Hintergrund</h3><div class="wallpapers"><button class="wallpaper-choice ${p.wall==='kmbd'?'active':''}" style="background-image:url('assets/wallpapers/kmbd-werbung.png')" onclick="setWall('kmbd')"></button><button class="wallpaper-choice ${p.wall==='blue'?'active':''}" style="background:linear-gradient(135deg,#07111f,#123c70,#06101c)" onclick="setWall('blue')"></button><button class="wallpaper-choice ${p.wall==='light'?'active':''}" style="background:linear-gradient(135deg,#dce7f7,#eef3fb,#c9d5e8)" onclick="setWall('light')"></button></div><p class="muted">Das gesendete KMBD-Bild ist als echter Desktop-Hintergrund eingebunden.</p></div></div>`}
function applyPrefs(){let p=load('prefsV2',{theme:'dark',wall:'kmbd'});document.body.classList.remove('theme-light','theme-contrast','wall-kmbd','wall-blue','wall-light');if(p.theme==='light')document.body.classList.add('theme-light');if(p.theme==='contrast')document.body.classList.add('theme-contrast');document.body.classList.add('wall-'+p.wall)}
function saveTheme(){let p=load('prefsV2',{theme:'dark',wall:'kmbd'});p.theme=$('#themeSel').value;store('prefsV2',p);applyPrefs();refresh('settings')}function setWall(w){let p=load('prefsV2',{theme:'dark',wall:'kmbd'});p.wall=w;store('prefsV2',p);applyPrefs();refresh('settings')}
function updateWidgets(){if(!$('#openCount'))return;$('#openCount').textContent=data.events.filter(e=>e.status!=='Abgeschlossen').length;$('#teamCount').textContent=data.personnel.length;$('#msgCount').textContent=data.chat.length;let next=[...data.events].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0];$('#nextEvent').innerHTML=next?`<b>${next.title}</b><br>${next.date} · ${next.time}<br>${next.place}`:'Keine Termine'}
$('#loginBtn').onclick=login;$('#loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#startBtn').onclick=()=>$('#startMenu').classList.toggle('hidden');$('#logoutBtn').onclick=()=>location.reload();applyPrefs();
