const users={
  KMBD:{password:'ausbilder1',role:'Ausbilder',name:'KMBD Ausbilder'},
  Leitung:{password:'leitung123',role:'Leitung',name:'KMBD Leitung'},
  Anwärter:{password:'test123',role:'Anwärter',name:'Anwärter Demo'}
};
let currentUser=null;let z=10;
const store=(k,v)=>localStorage.setItem('kmbd_'+k,JSON.stringify(v));
const load=(k,f)=>JSON.parse(localStorage.getItem('kmbd_'+k)||JSON.stringify(f));
let einsaetze=load('einsaetze',[{id:'E-2401',lage:'Verdächtiger Fund',ort:'Köln Altstadt',status:'In Prüfung',prio:'Mittel',leiter:'KMBD'}, {id:'E-2402',lage:'Absperrung / Beratung',ort:'Köln Deutz',status:'Abgeschlossen',prio:'Niedrig',leiter:'Leitung'}]);
let personal=load('personal',[{name:'M. Becker',rang:'Leitung',status:'Aktiv',qual:'Führungsdienst'}, {name:'T. Yilmaz',rang:'Ausbilder',status:'Aktiv',qual:'Ausbildung'}, {name:'J. Wolf',rang:'Anwärter',status:'Probezeit',qual:'Grundmodul'}]);
let chat=load('chat',[{user:'System',text:'Willkommen im internen KMBD-Chat.',time:'--:--'}]);
function login(){const u=username.value.trim(),p=password.value;if(users[u]?.password===p){currentUser={user:u,...users[u]};login.classList.add('hidden');desktop.classList.remove('hidden');roleLabel.textContent=`angemeldet als ${currentUser.name} · ${currentUser.role}`;openApp('dashboard')}else alert('Login falsch. Nutze KMBD / ausbilder1');}
function logout(){location.reload()}
function tick(){clock.textContent=new Date().toLocaleString('de-DE',{weekday:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'})}setInterval(tick,1000);tick();
function toggleStart(){startMenu.classList.toggle('hidden')}
function appTitle(id){return {dashboard:'Dashboard',einsatz:'Einsatzverwaltung',akten:'Personalakten',dienstplan:'Dienstplan',formulare:'Formulare',material:'Fahrzeuge & Material',lexikon:'KMBD Lexikon',chat:'Interner Chat',admin:'Verwaltung'}[id]||id}
function openApp(id){startMenu.classList.add('hidden');let w=document.getElementById('win_'+id);if(w){w.style.zIndex=++z;return}w=document.createElement('section');w.id='win_'+id;w.className='window';w.style.zIndex=++z;w.innerHTML=`<div class="win-head" onmousedown="drag(event,this.parentElement)"><strong>${appTitle(id)}</strong><div class="win-actions"><button onclick="minimize('${id}')">_</button><button onclick="closeApp('${id}')">×</button></div></div><div class="win-body">${render(id)}</div>`;windows.appendChild(w);addTask(id)}
function closeApp(id){document.getElementById('win_'+id)?.remove();document.getElementById('task_'+id)?.remove()}
function minimize(id){document.getElementById('win_'+id)?.classList.toggle('hidden')}
function addTask(id){if(document.getElementById('task_'+id))return;const b=document.createElement('button');b.id='task_'+id;b.textContent=appTitle(id);b.onclick=()=>minimize(id);openApps.appendChild(b)}
function drag(e,el){let ox=e.clientX-el.offsetLeft,oy=e.clientY-el.offsetTop;document.onmousemove=ev=>{el.style.left=Math.max(0,ev.clientX-ox)+'px';el.style.top=Math.max(45,ev.clientY-oy)+'px'};document.onmouseup=()=>document.onmousemove=null}
function rerender(id){document.querySelector(`#win_${id} .win-body`).innerHTML=render(id)}
function render(id){return ({dashboard,einsatz,akten,dienstplan,formulare,material,lexikon,chat:chatApp,admin}[id]||dashboard)()}
function dashboard(){return `<div class="grid"><div class="card"><h3>Aktive Einsätze</h3><div style="font-size:34px">${einsaetze.filter(e=>e.status!=='Abgeschlossen').length}</div><p class="muted">offene Vorgänge</p></div><div class="card"><h3>Personal</h3><div style="font-size:34px">${personal.length}</div><p class="muted">registrierte Mitglieder</p></div><div class="card"><h3>Chat</h3><div style="font-size:34px">${chat.length}</div><p class="muted">Nachrichten lokal gespeichert</p></div><div class="card"><h3>Status</h3><span class="pill">RP-Demo aktiv</span><p class="muted">Statische Version für GitHub Pages</p></div></div><h2>Letzte Einsätze</h2>${einsatzTable(false)}`}
function einsatzTable(actions=true){return `<table><tr><th>ID</th><th>Lage</th><th>Ort</th><th>Priorität</th><th>Status</th><th>Leiter</th></tr>${einsaetze.map(e=>`<tr><td>${e.id}</td><td>${e.lage}</td><td>${e.ort}</td><td>${e.prio}</td><td>${e.status}</td><td>${e.leiter}</td></tr>`).join('')}</table>`}
function einsatz(){return `<div class="split"><div class="card"><h3>Neuen RP-Einsatz erfassen</h3><div class="form-row"><input id="elage" placeholder="Lage / Titel"><input id="eort" placeholder="Ort"></div><div class="form-row"><select id="eprio"><option>Niedrig</option><option selected>Mittel</option><option>Hoch</option></select><select id="estatus"><option>In Prüfung</option><option>In Bearbeitung</option><option>Abgeschlossen</option></select></div><textarea id="enotiz" placeholder="Notiz für die Akte"></textarea><button onclick="addEinsatz()">Einsatz speichern</button></div><div class="card"><h3>Ablauf</h3><ol><li>Meldung aufnehmen</li><li>Leitung informieren</li><li>RP-Lage bewerten</li><li>Personal/Fahrzeug zuweisen</li><li>Dokumentation abschließen</li></ol><p class="muted">Keine realen Kampfmittel-Anleitungen, nur RP-Verwaltung.</p></div></div><h3>Einsatzliste</h3>${einsatzTable()}`}
function addEinsatz(){einsaetze.unshift({id:'E-'+Math.floor(1000+Math.random()*9000),lage:elage.value||'Neue Meldung',ort:eort.value||'Köln',prio:eprio.value,status:estatus.value,leiter:currentUser.user});store('einsaetze',einsaetze);rerender('einsatz');rerender('dashboard')}
function akten(){return `<div class="toolbar"><button onclick="addPerson()">Demo-Person hinzufügen</button></div><table><tr><th>Name</th><th>Rang</th><th>Status</th><th>Qualifikation</th></tr>${personal.map(p=>`<tr><td>${p.name}</td><td>${p.rang}</td><td>${p.status}</td><td>${p.qual}</td></tr>`).join('')}</table>`}
function addPerson(){personal.push({name:'Neue Person',rang:'Anwärter',status:'Aktiv',qual:'Grundmodul'});store('personal',personal);rerender('akten');rerender('dashboard')}
function dienstplan(){return `<table><tr><th>Tag</th><th>Dienst</th><th>Besetzung</th><th>Notiz</th></tr><tr><td>Montag</td><td>Ausbildung</td><td>Ausbilder + Anwärter</td><td>Grundlagen & Aktenpflege</td></tr><tr><td>Mittwoch</td><td>Bereitschaft</td><td>Leitung</td><td>RP-Einsatzfenster</td></tr><tr><td>Freitag</td><td>Übung</td><td>Alle</td><td>Szenario Köln</td></tr></table>`}
function formulare(){return `<div class="grid"><div class="card"><h3>KB-01 Einsatzmeldung</h3><p class="muted">Ersterfassung einer RP-Lage.</p><button onclick="alert('Formular KB-01 geöffnet – Demo')">Öffnen</button></div><div class="card"><h3>KB-02 Personalnotiz</h3><p class="muted">Interne Dokumentation.</p><button onclick="alert('Formular KB-02 geöffnet – Demo')">Öffnen</button></div><div class="card"><h3>KB-03 Ausbildungsnachweis</h3><p class="muted">Module, Status, Prüfungen.</p><button onclick="alert('Formular KB-03 geöffnet – Demo')">Öffnen</button></div><div class="card"><h3>KB-04 Fahrzeugprotokoll</h3><p class="muted">Fahrzeugstatus im RP.</p><button onclick="alert('Formular KB-04 geöffnet – Demo')">Öffnen</button></div><div class="card"><h3>KB-05 Abschlussbericht</h3><p class="muted">Zusammenfassung nach Einsatz.</p><button onclick="alert('Formular KB-05 geöffnet – Demo')">Öffnen</button></div></div>`}
function material(){return `<table><tr><th>Kennung</th><th>Typ</th><th>Status</th><th>Standort</th></tr><tr><td>KMBD-01</td><td>Einsatzfahrzeug</td><td class="ok">Verfügbar</td><td>Wache Köln</td></tr><tr><td>KMBD-02</td><td>Transport</td><td class="warn">Wartung</td><td>Werkstatt</td></tr><tr><td>Set-A</td><td>RP-Ausrüstung</td><td class="ok">Vollständig</td><td>Lager</td></tr></table>`}
function lexikon(){return `<div class="grid"><div class="card"><h3>RP-Einsatzführung</h3><p class="muted">Rollen, Meldewege und Dokumentation für den Server.</p></div><div class="card"><h3>Absperrung im RP</h3><p class="muted">Bereiche koordinieren, Lage sichern, Kommunikation führen.</p></div><div class="card"><h3>Ausbildung</h3><p class="muted">Anwärter, Ausbilder, Leitung, Prüfungsstand.</p></div><div class="card"><h3>Wichtig</h3><p class="muted">Dieses Lexikon enthält bewusst keine realen technischen Anleitungen.</p></div></div>`}
function chatApp(){return `<div class="chat"><div class="messages">${chat.map(m=>`<div class="msg"><b>${m.user}</b> <span class="muted">${m.time}</span><br>${m.text}</div>`).join('')}</div><div class="form-row" style="margin-top:10px"><input id="chatText" placeholder="Nachricht an interne KMBD-Gruppe"><button onclick="sendChat()">Senden</button></div></div>`}
function sendChat(){const t=chatText.value.trim();if(!t)return;chat.push({user:currentUser.user,text:t,time:new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})});store('chat',chat);rerender('chat');rerender('dashboard')}
function admin(){const locked=currentUser.role==='Anwärter';return `<div class="grid"><div class="card"><h3>Rollen</h3><p>Aktuelle Rolle: <span class="pill">${currentUser.role}</span></p><p class="muted">Leitung kann später Benutzer, Rechte und Akten verwalten.</p></div><div class="card"><h3>System</h3><p>Version: 0.2 RP-Demo</p><p>Speicher: Browser LocalStorage</p><button onclick="localStorage.clear();alert('Lokale Demo-Daten gelöscht');location.reload()">Demo-Daten zurücksetzen</button></div><div class="card"><h3>Zugriff</h3><p class="${locked?'warn':'ok'}">${locked?'Eingeschränkte Demo-Rechte':'Erweiterte Demo-Rechte'}</p></div></div>`}
